### ISSUE TITLE
add plot_dens

### ISSUE THREAD

**Issue by aloctavodia** [arviz-devs/arviz-plots#4]
https://python.arviz.org/en/stable/api/generated/arviz.plot_density.html

not clear if possible with plotcollection when input are lists of inferencedata

**Comment by OriolAbril** [comment]
Do we want a plot_dens with less elements in addition to plot_dist? plot_dist already supports multiple models without problem which was an important difference between plot_density and plot_posterior. It might be better to allow for turning off visual elements instead and have a single function instead of two separate ones.

**Comment by OriolAbril** [comment]
👌🏿. I'll open an issue about omitting/removing visual elements from plots instead.
